### ISSUE TITLE
Support Shapeshift.io authorization header

### ISSUE THREAD

**Issue by eodgooch** [EdgeApp/edge-core-js#135]
Shapeshift's API is introducing a breaking change. This means we need to update the shapeshift api module to include the new "authorization" header and a dynamic bearer token. 

https://shapeshift.zendesk.com/hc/en-us/articles/360001186600-How-to-Authorize-Your-AUTHTOKEN-in-FireFox

**Comment by swansontec** [comment]
This is now supported in our application and in our API. The app asks for ShapeShift login credentials if that is the only available exchange that can do the trade. In our API, you would do `account.swapConfig['shapeshift'].changeUserSettings({ accessToken: '...' })` to set this up.
